codecov:
  notify:
    wait_for_ci: false
    
coverage:
  status:
    project:
      default:
        target: 50% #overall project/ repo coverage
    patch:
      service:
        target: 41.67%
        threshold: 0.01%
        flags:
          - service
      controller:
        target: auto
        flags:
          - controller      

comment:
  layout: "diff, flags, files"
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
  show_carryforward_flags: true 
  
flags:
  service:
    carryforward: false
    paths: 
      - app/Services
  controller:
    carryforward: false
    paths: 
      - app/Http/Controllers 
  main:
    carryforward: false

github_checks:
  annotations: true